version: '3'
services:
  travel-broker-frontend:
    image: "registry.hub.docker.com/linhdanghong/mams-travel-broker-admin"
    ports:
      - "80:80"
    depends_on:
      - travel-broker-engine
  travel-service:
    image: "registry.hub.docker.com/linhdanghong/mams-travel-agent:latest"
    ports:
      - "8081:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    depends_on:
      - travel-broker-engine
  ryanair-service:
    image: "registry.hub.docker.com/linhdanghong/mams-travel-provider:latest"
    ports:
      - "8082:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=ryanair"
    depends_on:
      - travel-broker-engine
  sheraton-service:
    image: "registry.hub.docker.com/linhdanghong/mams-travel-provider:latest"
    ports:
      - "8083:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=sheraton"
    depends_on:
      - travel-broker-engine
  travel-broker-engine:
    image: "registry.hub.docker.com/linhdanghong/mams-travel-broker:1.0"